---
- name: Install Git
  become: yes
  apt:
    name: git
    state: present
    update_cache: yes

- name: Configure Git global settings
  become: yes
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: system
  loop:
    - { name: "credential.helper", value: "cache --timeout=3600" }
    - { name: "core.fileMode", value: "false" }

